server:
  port: 8842
  servlet:
    context-path: /bazooka
log:
  level: debug

spring:
  data:
    hbase:
      quorum: 127.0.0.1:2185
      rootDir: file:///home/hbase/rootdir
      nodeParent: /home/hbase/zkData