server:
  port: 8842
  servlet:
    context-path: /bazooka
#elasticsearch:
#  host: 127.0.0.1
#  port: 9200
#  scheme: http
#  username:
#  password:
log:
  level: debug
spring:
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true