server:
  port: 8841
  servlet:
    context-path: /bazooka
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:32775/bazooka?useUnicode=true&characterEncoding=utf-8

test:
  value1: firstAgent
  value2: secondAgent
